### ISSUE TITLE
Site branding not applied in SiteGenerator from repository

### ISSUE THREAD

**Issue by qtzar** [avisi-cloud/structurizr-site-generatr#219]
When using the Serve option the workspace is built from the DSL before the site branding css file is generated, however when doing a Generate the workspace model is not built till after that stage resulting in the default site-branding css.

I'm going to work on resolving this but just wanted to report it first. I'm thinking that one possible way to resolve this would be to move the site-branding css file to the branch directory which would allow different branches to have different color schemes.

**Comment by dirkgroot** [comment]
It took me some puzzling to figure out what the problem is exactly. From what I understand now, I think that the issue is that currently, `style-branding.css` is a site-wide stylesheet, but it is generated for every branch. This means that if one would generate a site for multiple branches, and the last branch has no `generatr.style...` properties, the entire site will have default branding.

Do I understand the issue correctly?

**Comment by jp7677** [comment]
Yes, currently the branding style sheet will be regenerated with every branch, thus the last branch to process wins. This PR should make the branding stylesheets a branch specific asset.

**Comment by dirkgroot** [comment]
Okay, cool. Nice catch, @qtzar!
