### ISSUE TITLE
Q: Using locally - links lead to displaying file catalogue and not to correct index.html

### ISSUE THREAD

**Issue by chipbite** [avisi-cloud/structurizr-site-generatr#487]
I am not sure if this is a stupid question or not, but all links in the build point to the corresponding catalogues and when just browsing locally off of disk and not via a webserver, that means I get the catalogue file list whenever I click a link - and then I need to click on index.html to see how it was supposed to look, so to speak.

Is there a way to get it to build with "complete" links to the right index page instead of the catalogue, for when browsing locally off of disk?

Does my question make sense?
I have a nagging feeling I am missing something obvious here, sorry, I may need more coffeeeeee... :-)

**Comment by jp7677** [comment]
You need indeed run your own web server or use the embedded one (https://github.com/avisi-cloud/structurizr-site-generatr?tab=readme-ov-file#start-a-development-web-server-around-the-generated-website) to browse the resulting site.

**Comment by chipbite** [comment]
Aha! Duh, sorry. Thanks for the swift reply! Works a charm!

**Comment by mawid6** [comment]
Btw, @jp7677, curious - why?... why do you want to serve the site via a webserver... or rather - why do you need a webserver, is there some other capability where you need it, thus opting to design it as the default choice?

**Comment by jp7677** [comment]
The idea was from the beginning on to generated a site that can be hosted and not just about a bunch of documents to be distributed by e.g. zip archive. So we just ended up relying on the index.html being returned when requesting a path. I guess mostly because it is prettier. Having the local development allowed us later on to add hot-reloading, because who likes manually refreshing the browser window ;).

**Comment by chipbite** [comment]
Yeah, I realized the hot reloading as I was testing things out today. Nice.
Thanks!
