### ISSUE TITLE
Serve Hot Reload is not working

### ISSUE THREAD

**Issue by zhenya-yadlovskij** [avisi-cloud/structurizr-site-generatr#488]
Env: Windows 10 + WSL2 Ubutntu + Docker installed inside Ubuntu (not Docker Desktop)
Method: intalled through homebrew and runed with 'serve' command as both as runned as docker and mounted folder
Project: https://github.com/avisi-cloud/structurizr-site-generatr

Steps to reproduce:
- wsl
- git clone https://github.com/avisi-cloud/structurizr-site-generatr
- cd /docs/examples
- docker run -it --rm -v /mnt/c/projects/test/AaaC/structurizr-site-generatr/docs/example:/var/model -p 8080:8080 ghcr.io/avisi-cloud/structurizr-site-generatr serve -w workspace.dsl
- or structurizr-site-generatr serve -w workspace.dsl
- add new container to internet banking system
- open http://localhost:8080/master/internet-banking-system/container/

Actual Behaviuor:
- nothing is changed
- no messages in logs

Expected behaviour:
- message in logs
- content of the container view has been changed

**Comment by lances101** [comment]
Not a problem with the generator itself. 

This is an issue with WSL and Docker on Windows, mixing the filesystems becomes a bit messy. See https://github.com/microsoft/WSL/issues/4739

Either move your files directly to your WSL filesystem (it's what I do now), or mount your structurizr model to a different directory and sync it into the main model dir, i.e. via `unison`.

Something like `while :;do unison -batch /var/model-copy/ /var/model/;sleep 2;done` should work and keep your volume synced both ways. You could create a Docker image on top of this one for ease, or potentially a side-container with unison + that script so that it syncs up the files for you. 

It's a dirty hack, but for the purposes of this generator should work just fine.

**Comment by jp7677** [comment]
Thanks a lot for the detailed answer @lances101 !
I guess this can be closed.
